/**
 * Country → flag emoji map, sourced from the `courses` table
 * (SELECT DISTINCT country, flag FROM courses) as of 2026-04-17.
 * Covers all 149 countries currently present in the database.
 */
export const COUNTRY_FLAGS: Record<string, string> = {
  Afghanistan: '🇦🇫',
  Albania: '🇦🇱',
  Algeria: '🇩🇿',
  Andorra: '🇦🇩',
  Angola: '🇦🇴',
  Argentina: '🇦🇷',
  Australia: '🇦🇺',
  Austria: '🇦🇹',
  Azerbaijan: '🇦🇿',
  Bahamas: '🇧🇸',
  Bahrain: '🇧🇭',
  Bangladesh: '🇧🇩',
  Barbados: '🇧🇧',
  Belarus: '🇧🇾',
  Belgium: '🇧🇪',
  Belize: '🇧🇿',
  Benin: '🇧🇯',
  Bermuda: '🇧🇲',
  Bhutan: '🇧🇹',
  Bolivia: '🇧🇴',
  Botswana: '🇧🇼',
  Brazil: '🇧🇷',
  Brunei: '🇧🇳',
  Bulgaria: '🇧🇬',
  Burundi: '🇧🇮',
  Cambodia: '🇰🇭',
  Cameroon: '🇨🇲',
  Canada: '🇨🇦',
  'Cayman Islands': '🇰🇾',
  Chad: '🇹🇩',
  Chile: '🇨🇱',
  China: '🇨🇳',
  Colombia: '🇨🇴',
  'Costa Rica': '🇨🇷',
  Croatia: '🇭🇷',
  Cuba: '🇨🇺',
  Cyprus: '🇨🇾',
  'Czech Republic': '🇨🇿',
  Denmark: '🇩🇰',
  'Dominican Republic': '🇩🇴',
  Ecuador: '🇪🇨',
  Egypt: '🇪🇬',
  'El Salvador': '🇸🇻',
  England: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Equatorial Guinea': '🇬🇶',
  Estonia: '🇪🇪',
  Ethiopia: '🇪🇹',
  Fiji: '🇫🇯',
  Finland: '🇫🇮',
  France: '🇫🇷',
  Georgia: '🇬🇪',
  Germany: '🇩🇪',
  Ghana: '🇬🇭',
  Greece: '🇬🇷',
  Guatemala: '🇬🇹',
  Guyana: '🇬🇾',
  Haiti: '🇭🇹',
  Honduras: '🇭🇳',
  'Hong Kong': '🇭🇰',
  Hungary: '🇭🇺',
  Iceland: '🇮🇸',
  India: '🇮🇳',
  Indonesia: '🇮🇩',
  Iran: '🇮🇷',
  Ireland: '🇮🇪',
  Israel: '🇮🇱',
  Italy: '🇮🇹',
  Jamaica: '🇯🇲',
  Japan: '🇯🇵',
  Jordan: '🇯🇴',
  Kazakhstan: '🇰🇿',
  Kenya: '🇰🇪',
  Kuwait: '🇰🇼',
  Laos: '🇱🇦',
  Latvia: '🇱🇻',
  Lebanon: '🇱🇧',
  Lithuania: '🇱🇹',
  Luxembourg: '🇱🇺',
  Macau: '🇲🇴',
  Madagascar: '🇲🇬',
  Malawi: '🇲🇼',
  Malaysia: '🇲🇾',
  Maldives: '🇲🇻',
  Malta: '🇲🇹',
  Mauritius: '🇲🇺',
  Mexico: '🇲🇽',
  Morocco: '🇲🇦',
  Mozambique: '🇲🇿',
  Myanmar: '🇲🇲',
  Namibia: '🇳🇦',
  Netherlands: '🇳🇱',
  'New Zealand': '🇳🇿',
  Nicaragua: '🇳🇮',
  Nigeria: '🇳🇬',
  'Northern Ireland': '🇬🇧',
  Norway: '🇳🇴',
  Oman: '🇴🇲',
  Pakistan: '🇵🇰',
  Panama: '🇵🇦',
  'Papua New Guinea': '🇵🇬',
  Paraguay: '🇵🇾',
  Peru: '🇵🇪',
  Philippines: '🇵🇭',
  Poland: '🇵🇱',
  Portugal: '🇵🇹',
  'Puerto Rico': '🇵🇷',
  Qatar: '🇶🇦',
  Romania: '🇷🇴',
  Russia: '🇷🇺',
  Rwanda: '🇷🇼',
  'Saint Kitts and Nevis': '🇰🇳',
  'Saint Lucia': '🇱🇨',
  Samoa: '🇼🇸',
  'Saudi Arabia': '🇸🇦',
  Scotland: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  Senegal: '🇸🇳',
  Serbia: '🇷🇸',
  Seychelles: '🇸🇨',
  'Sierra Leone': '🇸🇱',
  Singapore: '🇸🇬',
  Slovakia: '🇸🇰',
  Slovenia: '🇸🇮',
  'Solomon Islands': '🇸🇧',
  'South Africa': '🇿🇦',
  'South Korea': '🇰🇷',
  Spain: '🇪🇸',
  'Sri Lanka': '🇱🇰',
  Suriname: '🇸🇷',
  Sweden: '🇸🇪',
  Switzerland: '🇨🇭',
  Taiwan: '🇹🇼',
  Tanzania: '🇹🇿',
  Thailand: '🇹🇭',
  Togo: '🇹🇬',
  'Trinidad and Tobago': '🇹🇹',
  Tunisia: '🇹🇳',
  Turkey: '🇹🇷',
  Uganda: '🇺🇬',
  Ukraine: '🇺🇦',
  'United Arab Emirates': '🇦🇪',
  Uruguay: '🇺🇾',
  USA: '🇺🇸',
  Uzbekistan: '🇺🇿',
  Vanuatu: '🇻🇺',
  Venezuela: '🇻🇪',
  Vietnam: '🇻🇳',
  Wales: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  Zambia: '🇿🇲',
  Zimbabwe: '🇿🇼',
}

/** Alphabetically sorted country names (all 149). */
export const COUNTRY_NAMES: string[] = Object.keys(COUNTRY_FLAGS).sort((a, b) => a.localeCompare(b))

/** Dropdown options: `{ value: 'Japan', label: '🇯🇵 Japan' }`, sorted by name. */
export const COUNTRY_OPTIONS: { value: string; label: string }[] = COUNTRY_NAMES.map(name => ({
  value: name,
  label: `${COUNTRY_FLAGS[name]} ${name}`,
}))
